import Foundation
import Testing
@testable import PatternsmithCore

/// Verifies `MTPExporter` byte-for-byte against reference `.mtp` files produced
/// by the official `tracker-lib` writer. The fixtures are generated by
/// `scratchpad/oracle.mjs` into `Tests/Fixtures/mtp_vectors.json`.
@Suite("MTP export")
struct MTPExporterTests {
    // MARK: Fixture model

    struct Vectors: Codable { let cases: [Case] }
    struct Case: Codable {
        let name: String
        let header: Header
        let crc: UInt32
        let tracks: [TrackSpec]
        let expectedBase64: String
    }
    struct Header: Codable {
        let idFile: String
        let type: Int
        let fwVersion: [UInt8]
        let fileStructureVersion: [UInt8]
        let size: Int
    }
    struct TrackSpec: Codable { let length: Int; let steps: [StepSpec] }
    struct StepSpec: Codable { let note: Int; let instrument: Int; let fx0: Lane; let fx1: Lane }
    struct Lane: Codable { let type: Int; let value: Int }

    static func loadVectors() throws -> Vectors {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // PatternsmithCoreTests
            .deletingLastPathComponent() // Tests
            .appendingPathComponent("Fixtures/mtp_vectors.json")
        return try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }

    // MARK: Mapping

    func makePattern(_ c: Case) -> Pattern {
        let tracks = c.tracks.map { spec in
            Track(
                name: "T",
                length: spec.length,
                steps: spec.steps.map { s in
                    Step(
                        note: Note(rawValue: s.note)!,
                        instrument: s.instrument,
                        fx: [
                            FXCommand(type: FXType(rawValue: s.fx0.type)!, value: s.fx0.value),
                            FXCommand(type: FXType(rawValue: s.fx1.type)!, value: s.fx1.value),
                        ]
                    )
                }
            )
        }
        return Pattern(metadata: PatternMetadata(name: c.name), device: .trackerPlus, tracks: tracks)
    }

    func options(_ h: Header, crc: UInt32) -> MTPExportOptions {
        MTPExportOptions(
            idFile: h.idFile,
            type: h.type,
            fwVersion: h.fwVersion,
            fileStructureVersion: h.fileStructureVersion,
            size: h.size,
            crc: crc
        )
    }

    // MARK: Tests

    @Test("Swift export matches tracker-lib byte-for-byte")
    func matchesOracle() throws {
        let vectors = try Self.loadVectors()
        #expect(vectors.cases.count == 3)

        for c in vectors.cases {
            let pattern = makePattern(c)
            let data = MTPExporter.export(pattern, options: options(c.header, crc: c.crc))
            let expected = Data(base64Encoded: c.expectedBase64)!

            #expect(data.count == expected.count, "\(c.name): size \(data.count) vs \(expected.count)")
            #expect(data == expected, "\(c.name): bytes differ from tracker-lib reference")
        }
    }

    @Test("16-track export has the expected total size")
    func sixteenTrackSize() {
        let pattern = DeviceProfile.trackerPlus.makeEmptyPattern(name: "X", stepCount: 32)
        let data = MTPExporter.export(pattern)
        // 14 header + 2 pad + 12 unused + 16 × (1 + 128×6) + 4 crc
        #expect(data.count == 14 + 2 + 12 + 16 * (1 + 128 * 6) + 4)
        #expect(data.count == 12336)
    }

    @Test("CRC-32 matches the standard check value")
    func crc32KnownAnswer() {
        // "123456789" → 0xCBF43926 (standard CRC-32 check value).
        #expect(CRC32.checksum(Array("123456789".utf8)) == 0xCBF4_3926)
    }
}
